// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvmfeAjtQmFDB7viduVUNDkqxEC2_uFM',
    appId: '1:870895772884:web:ba51ae62567dfae5cbc741',
    messagingSenderId: '870895772884',
    projectId: 'todoapp-49686',
    authDomain: 'todoapp-49686.firebaseapp.com',
    storageBucket: 'todoapp-49686.appspot.com',
    measurementId: 'G-FLEWWKP92P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswFybFscxu2wNHAVVCAtrEK9DOvmLCJY',
    appId: '1:870895772884:android:7d6208e5b5aec13dcbc741',
    messagingSenderId: '870895772884',
    projectId: 'todoapp-49686',
    storageBucket: 'todoapp-49686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAmW5g5-oi9adfr1IMKC4sJey3SidaULc',
    appId: '1:870895772884:ios:4ecfbc73890b1b19cbc741',
    messagingSenderId: '870895772884',
    projectId: 'todoapp-49686',
    storageBucket: 'todoapp-49686.appspot.com',
    iosClientId: '870895772884-f7925eietj1e7jn37jf0cufb79nkl8ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAmW5g5-oi9adfr1IMKC4sJey3SidaULc',
    appId: '1:870895772884:ios:4ecfbc73890b1b19cbc741',
    messagingSenderId: '870895772884',
    projectId: 'todoapp-49686',
    storageBucket: 'todoapp-49686.appspot.com',
    iosClientId: '870895772884-f7925eietj1e7jn37jf0cufb79nkl8ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
